#pragma once

#define SLOTS_PER_SLICE 20
#define N_SLICES 6
#define TOTAL_SLOTS 121

#define NEOPIXEL_PIO_NO    0
#define NEOPIXEL_PIO_SM    0
#define NEOPIXEL_PIO_PIN   2

#define BUTTON_MATRIX_I2C_PERIPH i2c0
#define BUTTON_MATRIX_I2C_SPEED  400000U
#define BUTTON_MATRIX_I2C_PIN_SDA 4
#define BUTTON_MATRIX_I2C_PIN_SCL 5
#define BUTTON_MATRIX_I2C_ADDR_0 0x20
#define BUTTON_MATRIX_I2C_ADDR_1 0x21
#define BUTTON_MATRIX_I2C_ADDR_2 0x22
#define BUTTON_MATRIX_I2C_ADDR_3 0x23
#define BUTTON_MATRIX_I2C_ADDR_4 0x24
#define BUTTON_MATRIX_I2C_ADDR_5 0x25
